# Generated by Django 3.0.1 on 2019-12-22 13:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20191222_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 22, 13, 41, 21, 174828, tzinfo=utc)),
        ),
    ]
